version: '3.8'
services:
  product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product
    ports:
      - ${APP_PORT:-80}:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=product-db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=product-redis
    volumes:
      - .:/var/www
    depends_on:
      - product-db
    networks:
      - product-network

  product-db:
    image: mysql:8-debian
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: product-db
    ports:
      - "${DB_EXTERNAL_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=mysqlroot
    volumes:
      - product-db-mysql:/var/lib/mysql
    networks:
      - product-network

  product-redis:
    image: redis:7.2.5-alpine
    container_name: product-redis
    volumes:
      - product-db-redis:/data
    networks:
      - product-network

networks:
  product-network:
    driver: bridge

volumes:
  product-db-mysql:
    driver: local
  product-db-redis:
    driver: local
